services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:
      - mailpit

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"

  # solvearr:
  #   image: ghcr.io/flaresolverr/flaresolverr:latest
  #   ports:
  #     - "8191:8191"
  #   environment:
  #     - LOG_LEVEL=info
